### ISSUE TITLE
How to use it on client side

### ISSUE THREAD

**Issue by Sunil178** [bytedance/unpub#39]
It's community is not that much strong. And on it's documentation there is nothing explanation about how to use it on client side

**Comment by sikandernoori** [comment]
@Sunil178 did you find solution how to use packages hosted on unpub in pubspec.yaml ?

**Comment by viliusvig** [comment]
You can you the following snippet as an example:

```yml
dependencies:
  transmogrify:
    hosted:
      name: transmogrify
      url: http://some-package-server.com
    version: ^1.0.0
```
